/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherDishCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherDishCollection (0 custom class methods, 2 custom properties)

#import "GTLAramarkHelperMenuFetcherDishCollection.h"

#import "GTLAramarkHelperMenuFetcherDish.h"

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherDishCollection
//

@implementation GTLAramarkHelperMenuFetcherDishCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLAramarkHelperMenuFetcherDish class]
  };
  return map;
}

@end
