/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherPeriod.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherPeriod (0 custom class methods, 3 custom properties)

#import "GTLAramarkHelperMenuFetcherPeriod.h"

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherPeriod
//

@implementation GTLAramarkHelperMenuFetcherPeriod
@dynamic entityKey, name, selectDate;
@end
