/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherCategory.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherCategory (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherCategory
//

@interface GTLAramarkHelperMenuFetcherCategory : GTLObject
@property (nonatomic, copy) NSString *entityKey;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *parent;
@end
