/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherCategoryCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherCategoryCollection (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAramarkHelperMenuFetcherCategory;

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherCategoryCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLAramarkHelperMenuFetcherCategoryCollection : GTLCollectionObject
@property (nonatomic, retain) NSArray *items;  // of GTLAramarkHelperMenuFetcherCategory
@property (nonatomic, copy) NSString *nextPageToken;
@end
