/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherDish.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherDish (0 custom class methods, 3 custom properties)

#import "GTLAramarkHelperMenuFetcherDish.h"

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherDish
//

@implementation GTLAramarkHelperMenuFetcherDish
@dynamic entityKey, name, parent;
@end
