/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcher.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API

#import "GTLAramarkHelperMenuFetcherConstants.h"

#import "GTLAramarkHelperMenuFetcherCategory.h"
#import "GTLAramarkHelperMenuFetcherCategoryCollection.h"
#import "GTLAramarkHelperMenuFetcherDish.h"
#import "GTLAramarkHelperMenuFetcherDishCollection.h"
#import "GTLAramarkHelperMenuFetcherPeriod.h"
#import "GTLAramarkHelperMenuFetcherPeriodCollection.h"

#import "GTLQueryAramarkHelperMenuFetcher.h"
#import "GTLServiceAramarkHelperMenuFetcher.h"
