/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherCategory.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherCategory (0 custom class methods, 3 custom properties)

#import "GTLAramarkHelperMenuFetcherCategory.h"

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherCategory
//

@implementation GTLAramarkHelperMenuFetcherCategory
@dynamic entityKey, name, parent;
@end
