/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherPeriodCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherPeriodCollection (0 custom class methods, 2 custom properties)

#import "GTLAramarkHelperMenuFetcherPeriodCollection.h"

#import "GTLAramarkHelperMenuFetcherPeriod.h"

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherPeriodCollection
//

@implementation GTLAramarkHelperMenuFetcherPeriodCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLAramarkHelperMenuFetcherPeriod class]
  };
  return map;
}

@end
