/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherCategoryCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLAramarkHelperMenuFetcherCategoryCollection (0 custom class methods, 2 custom properties)

#import "GTLAramarkHelperMenuFetcherCategoryCollection.h"

#import "GTLAramarkHelperMenuFetcherCategory.h"

// ----------------------------------------------------------------------------
//
//   GTLAramarkHelperMenuFetcherCategoryCollection
//

@implementation GTLAramarkHelperMenuFetcherCategoryCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLAramarkHelperMenuFetcherCategory class]
  };
  return map;
}

@end
