/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAramarkHelperMenuFetcherConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API

#import "GTLAramarkHelperMenuFetcherConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAramarkHelperMenuFetcherUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
