/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAramarkHelperMenuFetcher.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLQueryAramarkHelperMenuFetcher (3 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryAramarkHelperMenuFetcher : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) long long limit;
@property (nonatomic, copy) NSString *order;
@property (nonatomic, copy) NSString *pageToken;
@property (nonatomic, copy) NSString *parent;
@property (nonatomic, copy) NSString *selectDate;

#pragma mark -
#pragma mark "category" methods
// These create a GTLQueryAramarkHelperMenuFetcher object.

// Method: aramarkHelperMenuFetcher.category.list
//  Optional:
//   limit: long long
//   order: NSString
//   pageToken: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAramarkHelperMenuFetcherUserinfoEmail
// Fetches a GTLAramarkHelperMenuFetcherCategoryCollection.
+ (instancetype)queryForCategoryListWithParent:(NSString *)parent;

#pragma mark -
#pragma mark "dish" methods
// These create a GTLQueryAramarkHelperMenuFetcher object.

// Method: aramarkHelperMenuFetcher.dish.list
//  Optional:
//   limit: long long
//   order: NSString
//   pageToken: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAramarkHelperMenuFetcherUserinfoEmail
// Fetches a GTLAramarkHelperMenuFetcherDishCollection.
+ (instancetype)queryForDishListWithParent:(NSString *)parent;

#pragma mark -
#pragma mark "period" methods
// These create a GTLQueryAramarkHelperMenuFetcher object.

// Method: aramarkHelperMenuFetcher.period.list
//  Optional:
//   limit: long long
//   order: NSString
//   pageToken: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAramarkHelperMenuFetcherUserinfoEmail
// Fetches a GTLAramarkHelperMenuFetcherPeriodCollection.
+ (instancetype)queryForPeriodListWithSelectDate:(NSString *)selectDate;

@end
