/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAramarkHelperMenuFetcher.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLQueryAramarkHelperMenuFetcher (3 custom class methods, 6 custom properties)

#import "GTLQueryAramarkHelperMenuFetcher.h"

#import "GTLAramarkHelperMenuFetcherCategoryCollection.h"
#import "GTLAramarkHelperMenuFetcherDishCollection.h"
#import "GTLAramarkHelperMenuFetcherPeriodCollection.h"

@implementation GTLQueryAramarkHelperMenuFetcher

@dynamic fields, limit, order, pageToken, parent, selectDate;

#pragma mark -
#pragma mark "category" methods
// These create a GTLQueryAramarkHelperMenuFetcher object.

+ (instancetype)queryForCategoryListWithParent:(NSString *)parent {
  NSString *methodName = @"aramarkHelperMenuFetcher.category.list";
  GTLQueryAramarkHelperMenuFetcher *query = [self queryWithMethodName:methodName];
  query.parent = parent;
  query.expectedObjectClass = [GTLAramarkHelperMenuFetcherCategoryCollection class];
  return query;
}

#pragma mark -
#pragma mark "dish" methods
// These create a GTLQueryAramarkHelperMenuFetcher object.

+ (instancetype)queryForDishListWithParent:(NSString *)parent {
  NSString *methodName = @"aramarkHelperMenuFetcher.dish.list";
  GTLQueryAramarkHelperMenuFetcher *query = [self queryWithMethodName:methodName];
  query.parent = parent;
  query.expectedObjectClass = [GTLAramarkHelperMenuFetcherDishCollection class];
  return query;
}

#pragma mark -
#pragma mark "period" methods
// These create a GTLQueryAramarkHelperMenuFetcher object.

+ (instancetype)queryForPeriodListWithSelectDate:(NSString *)selectDate {
  NSString *methodName = @"aramarkHelperMenuFetcher.period.list";
  GTLQueryAramarkHelperMenuFetcher *query = [self queryWithMethodName:methodName];
  query.selectDate = selectDate;
  query.expectedObjectClass = [GTLAramarkHelperMenuFetcherPeriodCollection class];
  return query;
}

@end
