/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLServiceAramarkHelperMenuFetcher.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   aramarkHelperMenuFetcher/v1
// Description:
//   Menu Fetcher API
// Classes:
//   GTLServiceAramarkHelperMenuFetcher (0 custom class methods, 0 custom properties)

#import "GTLAramarkHelperMenuFetcher.h"

@implementation GTLServiceAramarkHelperMenuFetcher

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQueryAramarkHelperMenuFetcher class],
    [GTLAramarkHelperMenuFetcherCategory class],
    [GTLAramarkHelperMenuFetcherCategoryCollection class],
    [GTLAramarkHelperMenuFetcherDish class],
    [GTLAramarkHelperMenuFetcherDishCollection class],
    [GTLAramarkHelperMenuFetcherPeriod class],
    [GTLAramarkHelperMenuFetcherPeriodCollection class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://aramark-helper-menu-fetcher.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
